### ISSUE TITLE
deeppy/cudarray can't find CUDA device anymore

### ISSUE THREAD

**Issue by genekogan** [andersbll/deeppy#24]
installed cudarray, added /usr/local/lib/ to LD_LIBRARY_PATH, and cuda (/usr/local/cuda-6.5/lib64/) to PATH, but when i run this in python:

```
import os
os.environ['CUDARRAY_BACKEND'] = 'cuda'
import deeppy
```

i get this traceback.

CUDArray: Failed to load CUDA back-end.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/deeppy/**init**.py", line 9, in <module>
  File "build/bdist.linux-x86_64/egg/deeppy/dataset/**init**.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/deeppy/dataset/infimnist.py", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/deeppy/base.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cudarray-0.1.dev-py2.7-linux-x86_64.egg/cudarray/_
_init__.py", line 29, in <module>
    wrap.cudart.initialize(_gpu_id)
  File "cudarray/wrap/cudart.pyx", line 4, in cudarray.wrap.cudart.initialize (./cudarray/wrap/cu
dart.cpp:671)
  File "cudarray/wrap/cudart.pyx", line 5, in cudarray.wrap.cudart.initialize (./cudarray/wrap/cu
dart.cpp:600)
  File "cudarray/wrap/cudart.pyx", line 12, in cudarray.wrap.cudart.cudaCheck (./cudarray/wrap/cu
dart.cpp:736)
ValueError: no CUDA-capable device is detected

this worked a few months ago -- could there be a problem between recent commits of deeppy/cudarray and cuda-6.5?  not exactly sure where this problem is coming from.

thanks!

**Comment by andersbll** [comment]
Hi! I haven't seen this before. I can't think of any changes that should cause such problems. Have you remembered to clean up the CUDArray folder with both `make clean` and `python setup.py clean` before the new installation? Also, make sure that the environment variable `CUDARRAY_DEVICE` is the correct id of your GPU (default is '0').

A brief web search on the error message also suggests [this](https://devtalk.nvidia.com/default/topic/536813/no-cuda-capable-device-is-detected/) and [this](http://superuser.com/questions/943034/no-cuda-capable-device-is-detected-using-ubuntu-12-04-4-server/943035).

**Comment by lynchkl** [comment]
@genekogan, have you had any luck troubleshooting this issue? I'm getting something similar on an AWS instance: 

> > > import os
> > > os.environ['CUDARRAY_BACKEND'] = 'cuda'
> > > import cudarray
> > > CUDArray: Failed to load CUDA back-end.
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/cudarray-0.1.dev-py2.7-linux-x86_64.egg/cudarray/**init**.py", line 29, in <module>
> > >     wrap.cudart.initialize(_gpu_id)
> > >   File "cudarray/wrap/cudart.pyx", line 4, in cudarray.wrap.cudart.initialize (./cudarray/wrap/cudart.cpp:698)
> > >   File "cudarray/wrap/cudart.pyx", line 5, in cudarray.wrap.cudart.initialize (./cudarray/wrap/cudart.cpp:627)
> > >   File "cudarray/wrap/cudart.pyx", line 12, in cudarray.wrap.cudart.cudaCheck (./cudarray/wrap/cudart.cpp:763)
> > > ValueError: no CUDA-capable device is detected
